"""add username

Revision ID: 802d177934f3
Revises: 5de0698c3219
Create Date: 2022-10-30 22:15:56.491655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802d177934f3'
down_revision = '5de0698c3219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
