"""add like_count

Revision ID: ad9c31da2cdf
Revises: c7de913a188e
Create Date: 2022-11-29 20:24:01.578069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9c31da2cdf'
down_revision = 'c7de913a188e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('like_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'like_count')
    # ### end Alembic commands ###
