"""add tags

Revision ID: ae3348d1cde2
Revises: 802d177934f3
Create Date: 2022-11-28 18:59:36.314655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3348d1cde2'
down_revision = '802d177934f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
